<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<AssemblyName>RetryProxy</AssemblyName>
		<RootNamespace>RetryProxy</RootNamespace>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net9.0-windows10.0.22621.0</TargetFramework>
		<UseWPF>true</UseWPF>
		<UseWindowsForms>true</UseWindowsForms>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<ApplicationIcon>Resources\Images\logo.ico</ApplicationIcon>
		<DebugType>embedded</DebugType>
	</PropertyGroup>

	<ItemGroup>
		<Resource Include="Resources\Images\*.png" />
		<Resource Include="Resources\Images\*.jpg" />
		<Resource Include="Resources\Images\*.ico" />
		<Resource Include="Resources\Fonts\*.ttf" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.4" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.4" />
		<PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.4" />
		<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.4" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="9.0.4" />
		<PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.122" />
		<PackageReference Include="Semver" Version="3.0.0" />
		<PackageReference Include="System.Drawing.Common" Version="10.0.7" />
		<PackageReference Include="Vanara.PInvoke.NtDll" Version="4.1.3" />
		<PackageReference Include="Vanara.PInvoke.SHCore" Version="4.1.3" />
		<PackageReference Include="Vanara.PInvoke.User32" Version="4.1.3" />
		<PackageReference Include="WPF-UI" Version="4.3.0" />
		<PackageReference Include="WPF-UI.DependencyInjection" Version="4.3.0" />
		<PackageReference Include="WPF-UI.Tray" Version="4.3.0" />
		<PackageReference Include="WPF-UI.Violeta" Version="4.3.0.3" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\RetryProxy.Core\RetryProxy.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Update="User\I18n\**">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
		<_DeploymentManifestIconFile Remove="Resources\Images\logo.ico" />
	</ItemGroup>

</Project>
