using System.Collections.Generic;

namespace RetryProxy.Core.KeepAlive;

/// <summary>保活探测随机抽取的 250 道初级 Java 面试题（对应 java_questions.rs）。</summary>
public static class JavaQuestions
{
    public static readonly IReadOnlyList<string> All = new[]
    {
        "Java 的跨平台能力是如何实现的？",
        "JDK、JRE 和 JVM 各自负责什么？",
        "Java 源文件编译后会生成什么文件？",
        "Java 程序的 main 方法为什么声明为 static？",
        "Java 有哪些基本数据类型？",
        "int 和 long 有什么区别？",
        "float 和 double 有什么区别？",
        "char 和 String 有什么区别？",
        "局部变量使用前为什么必须初始化？",
        "成员变量和局部变量的默认值有什么区别？",
        "Java 中的自动类型转换是什么？",
        "强制类型转换可能造成什么问题？",
        "整数相除为什么可能得不到小数？",
        "自增运算符放在变量前后有什么区别？",
        "逻辑与和短路与有什么区别？",
        "逻辑或和短路或有什么区别？",
        "三元运算符适合解决什么问题？",
        "switch 和 if 有什么使用区别？",
        "break 和 continue 有什么区别？",
        "for 循环和 while 循环分别适合什么场景？",
        "增强 for 循环有哪些使用限制？",
        "Java 数组创建后还能改变长度吗？",
        "数组下标为什么要检查边界？",
        "基本类型参数传递后能直接修改调用者的变量吗？",
        "为什么说 Java 只有值传递？",
        "面向对象的封装是什么？",
        "面向对象的继承是什么？",
        "面向对象的多态是什么？",
        "类和对象有什么区别？",
        "构造方法和普通方法有什么区别？",
        "什么时候编译器会提供默认构造方法？",
        "this 关键字有哪些常见用途？",
        "super 关键字有哪些常见用途？",
        "父类和子类构造方法的执行顺序是什么？",
        "方法重载需要满足什么条件？",
        "方法重写需要满足什么条件？",
        "方法重载和方法重写有什么区别？",
        "private、默认访问、protected 和 public 的访问范围有什么区别？",
        "static 修饰的成员属于类还是对象？",
        "静态方法为什么不能直接访问实例变量？",
        "final 修饰变量、方法和类分别表示什么？",
        "抽象类为什么不能直接实例化？",
        "接口和抽象类有什么区别？",
        "一个 Java 类可以实现多个接口吗？",
        "接口中的 default 方法有什么作用？",
        "向上转型和向下转型有什么区别？",
        "instanceof 运算符解决什么问题？",
        "Object 类中的 toString 方法有什么作用？",
        "组合和继承分别表示什么关系？",
        "内部类有哪些常见类型？",
        "String 对象为什么通常称为不可变对象？",
        "StringBuilder 和 StringBuffer 有什么区别？",
        "为什么循环内大量拼接字符串适合使用 StringBuilder？",
        "字符串比较中的 equals 和双等号有什么区别？",
        "字符串常量池有什么作用？",
        "new String 和直接使用字符串字面量有什么区别？",
        "String 的 length 方法返回的是什么长度？",
        "判断字符串为空时需要注意哪些情况？",
        "trim 和 strip 方法有什么区别？",
        "字符串 split 方法的参数为什么需要注意正则表达式？",
        "substring 方法如何确定截取范围？",
        "字符串 replace 和 replaceAll 有什么区别？",
        "Integer 和 int 有什么区别？",
        "自动装箱和自动拆箱是什么？",
        "对 null 包装类型进行拆箱会发生什么？",
        "比较两个 Integer 对象为什么应该避免直接使用双等号？",
        "Integer.parseInt 和 Integer.valueOf 有什么区别？",
        "BigDecimal 适合解决哪类精度问题？",
        "为什么不建议直接用 double 构造金额对应的 BigDecimal？",
        "BigDecimal 的 equals 和 compareTo 有什么区别？",
        "枚举类型适合表示什么数据？",
        "枚举对象可以包含字段和方法吗？",
        "可变参数在方法参数列表中有什么位置要求？",
        "Objects.equals 方法如何处理 null？",
        "深拷贝和浅拷贝有什么区别？",
        "Java 集合框架中的 List、Set 和 Map 各有什么特点？",
        "Collection 和 Collections 有什么区别？",
        "ArrayList 和 LinkedList 有什么区别？",
        "ArrayList 的 size 和内部容量有什么区别？",
        "为什么创建 ArrayList 时有时要指定初始容量？",
        "List 如何保持元素的插入顺序？",
        "Set 为什么通常不允许重复元素？",
        "HashSet 判断元素重复依赖哪些方法？",
        "TreeSet 如何确定元素的顺序？",
        "LinkedHashSet 有什么特点？",
        "HashMap 中的键和值能否为 null？",
        "HashMap 和 Hashtable 有什么区别？",
        "HashMap 为什么要求键的 equals 和 hashCode 保持一致？",
        "为什么不建议使用内容会变化的对象作为 HashMap 的键？",
        "LinkedHashMap 能保持什么顺序？",
        "TreeMap 和 HashMap 有什么区别？",
        "遍历 Map 有哪些常见方式？",
        "Iterator 的 remove 方法有什么用途？",
        "为什么遍历集合时直接删除元素可能发生异常？",
        "Arrays.asList 返回的列表为什么不能随意增删？",
        "List.of 创建的列表有哪些限制？",
        "Comparable 和 Comparator 有什么区别？",
        "Queue 接口适合哪些业务场景？",
        "Deque 如何分别用作队列和栈？",
        "PriorityQueue 中的元素会按什么规则取出？",
        "Java 泛型主要解决什么问题？",
        "泛型类和泛型方法有什么区别？",
        "泛型为什么不能直接使用 int 作为类型参数？",
        "泛型中的无界通配符有什么含义？",
        "泛型中的 extends 上界通配符有什么作用？",
        "泛型中的 super 下界通配符有什么作用？",
        "为什么 List<Integer> 不能直接赋给 List<Number>？",
        "什么是泛型类型擦除？",
        "Throwable、Exception 和 Error 有什么关系？",
        "受检异常和运行时异常有什么区别？",
        "try、catch 和 finally 分别有什么作用？",
        "多个 catch 语句的顺序需要注意什么？",
        "throw 和 throws 有什么区别？",
        "finally 中编写 return 为什么容易出问题？",
        "try-with-resources 如何帮助关闭资源？",
        "自定义异常通常需要继承什么类？",
        "捕获异常后为什么不应该直接忽略它？",
        "NullPointerException 常见的触发原因有哪些？",
        "NumberFormatException 通常在什么情况下出现？",
        "ClassCastException 通常在什么情况下出现？",
        "日期处理中 LocalDate 和 LocalDateTime 有什么区别？",
        "Instant 适合表达什么时间信息？",
        "ZoneId 在时间转换中有什么作用？",
        "DateTimeFormatter 与 SimpleDateFormat 在线程安全方面有什么区别？",
        "为什么记录时间时要关注时区？",
        "进程和线程有什么区别？",
        "Java 中创建线程有哪些常见方式？",
        "Thread 的 start 和 run 方法有什么区别？",
        "Runnable 和 Callable 有什么区别？",
        "线程有哪些基本状态？",
        "sleep 和 wait 有什么区别？",
        "join 方法有什么作用？",
        "interrupt 是否会立即强制终止线程？",
        "为什么不建议使用 Thread.stop 停止线程？",
        "线程安全通常指什么？",
        "共享可变变量为什么容易产生并发问题？",
        "synchronized 可以用在哪些位置？",
        "实例同步方法和静态同步方法锁住的对象有什么区别？",
        "volatile 主要保证什么性质？",
        "volatile 能保证自增操作的原子性吗？",
        "原子类 AtomicInteger 适合解决什么问题？",
        "ReentrantLock 与 synchronized 有哪些使用区别？",
        "使用显式锁时为什么通常在 finally 中释放锁？",
        "死锁发生时通常涉及哪些条件？",
        "线程池相比频繁创建线程有什么好处？",
        "线程池中的任务队列有什么作用？",
        "Future 的 get 方法为什么可能阻塞？",
        "CountDownLatch 适合什么协作场景？",
        "Semaphore 如何限制同时访问资源的线程数量？",
        "ThreadLocal 使用结束后为什么建议 remove？",
        "Java 字节流和字符流有什么区别？",
        "InputStream 和 OutputStream 分别负责什么？",
        "Reader 和 Writer 适合处理什么内容？",
        "BufferedReader 和 BufferedWriter 为什么能改善读写效率？",
        "使用文件流后为什么必须关闭资源？",
        "处理中文文本时为什么需要明确字符编码？",
        "UTF-8 和 Java char 的表示方式有什么区别？",
        "File 类对象是否一定代表已经存在的文件？",
        "Path 和 Files 在文件操作中有什么作用？",
        "相对路径和绝对路径有什么区别？",
        "序列化和反序列化是什么？",
        "Serializable 接口有什么作用？",
        "transient 关键字如何影响默认序列化？",
        "为什么不应随意反序列化不可信数据？",
        "JVM 堆和线程栈主要保存什么？",
        "对象引用和对象本身有什么区别？",
        "垃圾回收主要回收哪类对象？",
        "对象不可达是否意味着它会立即被回收？",
        "内存泄漏和内存溢出有什么区别？",
        "OutOfMemoryError 与 StackOverflowError 有什么区别？",
        "递归调用缺少结束条件可能造成什么问题？",
        "类加载一般包含哪些阶段？",
        "类的静态代码块通常什么时候执行？",
        "反射可以在运行时获得哪些类信息？",
        "反射相比直接调用为什么需要谨慎使用？",
        "Lambda 表达式主要简化了哪类代码？",
        "函数式接口需要满足什么条件？",
        "FunctionalInterface 注解有什么作用？",
        "方法引用与 Lambda 表达式有什么关系？",
        "Stream 和集合本身有什么区别？",
        "Stream 的中间操作和终止操作有什么区别？",
        "Stream 的 filter 方法有什么作用？",
        "Stream 的 map 和 flatMap 有什么区别？",
        "Stream 的 collect 常用于什么场景？",
        "Stream 的 distinct 如何判断重复？",
        "Stream 的 sorted 如何指定排序规则？",
        "findFirst 与 findAny 有什么区别？",
        "为什么同一个 Stream 不能重复执行终止操作？",
        "parallelStream 为什么不一定比普通 Stream 更快？",
        "Optional 主要解决什么代码表达问题？",
        "Optional 的 of 和 ofNullable 有什么区别？",
        "Optional 的 orElse 和 orElseGet 有什么区别？",
        "Java 注解通常用来表达什么信息？",
        "Override 注解能帮助发现什么错误？",
        "注解的 Retention 策略有哪些常见取值？",
        "record 类型适合表达什么数据？",
        "record 自动生成哪些常见方法？",
        "单例模式希望解决什么问题？",
        "工厂模式如何减少对象创建代码的耦合？",
        "策略模式适合替代哪类复杂条件分支？",
        "HTTP 请求和响应分别包含哪些基本部分？",
        "GET 和 POST 的常见使用语义有什么区别？",
        "HTTP 状态码 200、400、401、404 和 500 分别表示什么？",
        "Cookie 和 Session 有什么区别？",
        "JSON 为什么适合用于接口数据交换？",
        "Java Web 中的 Servlet 主要负责什么？",
        "过滤器 Filter 可以处理哪些公共逻辑？",
        "Spring 的控制反转是什么意思？",
        "Spring 的依赖注入解决什么问题？",
        "构造器注入有哪些常见优点？",
        "Component、Service 和 Repository 注解有什么关系？",
        "Controller 和 RestController 有什么区别？",
        "Spring Bean 的单例作用域表示什么？",
        "Spring 单例 Bean 是否自动具备线程安全性？",
        "RequestParam 和 PathVariable 有什么区别？",
        "RequestBody 注解通常用于什么场景？",
        "统一异常处理能解决哪些重复代码问题？",
        "Spring Boot 自动配置的基本作用是什么？",
        "application.properties 和 application.yml 用来配置什么？",
        "不同环境使用不同配置文件有什么好处？",
        "数据库事务的 ACID 分别表示什么？",
        "JDBC 中 Connection、Statement 和 ResultSet 分别负责什么？",
        "PreparedStatement 为什么通常比字符串拼接 SQL 更安全？",
        "数据库连接池主要解决什么问题？",
        "为什么数据库操作结束后要及时归还连接？",
        "SQL 的 WHERE 和 HAVING 有什么区别？",
        "数据库主键和唯一约束有什么区别？",
        "数据库索引为什么能改善部分查询的性能？",
        "为什么数据库索引不是越多越好？",
        "INNER JOIN 和 LEFT JOIN 有什么区别？",
        "事务的提交和回滚分别有什么作用？",
        "什么是 SQL 注入，开发时怎样避免？",
        "分页查询为什么需要稳定的排序条件？",
        "Maven 的 pom.xml 主要描述什么信息？",
        "Maven 的依赖传递是什么意思？",
        "Maven 的 compile 和 test 依赖范围有什么区别？",
        "Maven 的 clean、test 和 package 分别做什么？",
        "单元测试和集成测试有什么区别？",
        "JUnit 中的断言为什么比打印输出更适合验证结果？",
        "测试方法为什么应尽量相互独立？",
        "为什么测试中通常不直接使用生产数据库？",
        "日志中的 DEBUG、INFO、WARN 和 ERROR 通常如何选择？",
        "为什么日志中不应该打印密码和完整访问密钥？",
        "定位异常时为什么要保留异常堆栈？",
        "Git 的工作区、暂存区和本地仓库有什么区别？",
        "Git 的 commit 和 push 有什么区别？",
        "代码审查通常重点检查哪些内容？",
        "为什么方法应尽量只承担一个清晰的职责？",
        "为什么使用具有业务含义的变量名比缩写更容易维护？",
        "收到用户输入后，为什么需要进行边界和格式校验？",
    };

    public static int Count => All.Count;
}
